version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    

  ia:
    build:
      context: .
      dockerfile: backend/IA/Dockerfile.IA
    ports:
      - "5001:5001"
    depends_on:
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ia
    

