# backend/ia/Dockerfile.IA
FROM node:18

WORKDIR /app
COPY backend/package*.json ./
RUN npm install

COPY backend/IA/train.mjs .
COPY backend/IA/recoveD.mjs .

EXPOSE 5001
CMD ["node", "recoveD.mjs"]
